In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import os, sys
import pandas as pd
import sklearn
import sklearn.svm, sklearn.discriminant_analysis
import time
import scipy.stats


root = '/usr/local/serenceslab/maggie/shapeDim/'
sys.path.append(os.path.join(root, 'Analysis'))
from code_utils import file_utils, data_utils, plot_utils, stats_utils, grid_utils

In [3]:
ss =1
main_labels = data_utils.load_main_task_labels(ss)
rep_labels = data_utils.load_repeat_task_labels(ss)
concat_labels = pd.concat([main_labels, rep_labels], axis=0)

In [4]:
main_labels.keys()

Index(['sub', 'sess', 'part', 'run_in_part', 'run_overall', 'task', 'map',
       'run_difficulty', 'trial_in_run', 'trial_overall', 'rt', 'correct_resp',
       'resp', 'timeout', 'category_unmapped', 'resp_unmapped',
       'subject_correct', 'is_main_grid', 'ptx', 'pty', 'quadrant',
       'dist_from_center', 'dist_from_bound1', 'dist_from_bound2',
       'dist_from_bound3', 'categ_task1', 'categ_task2', 'categ_task3'],
      dtype='object')

In [5]:
rep_labels.keys()

Index(['sub', 'sess', 'run_in_sess', 'run_overall', 'map', 'run_difficulty',
       'task', 'trial_in_run', 'trial_overall', 'rt', 'correct_resp', 'resp',
       'timeout', 'subject_correct', 'is_repeat', 'dist_from_previous',
       'is_main_grid', 'ptx', 'pty', 'quadrant', 'dist_from_center',
       'dist_from_bound1', 'dist_from_bound2', 'dist_from_bound3',
       'categ_task1', 'categ_task2', 'categ_task3'],
      dtype='object')

In [6]:
concat_labels.keys()

Index(['sub', 'sess', 'part', 'run_in_part', 'run_overall', 'task', 'map',
       'run_difficulty', 'trial_in_run', 'trial_overall', 'rt', 'correct_resp',
       'resp', 'timeout', 'category_unmapped', 'resp_unmapped',
       'subject_correct', 'is_main_grid', 'ptx', 'pty', 'quadrant',
       'dist_from_center', 'dist_from_bound1', 'dist_from_bound2',
       'dist_from_bound3', 'categ_task1', 'categ_task2', 'categ_task3',
       'run_in_sess', 'is_repeat', 'dist_from_previous'],
      dtype='object')

In [7]:
for kk in concat_labels.keys():
    print(kk)
    print(np.sum(np.isnan(concat_labels[kk])))
    print(np.unique(concat_labels[kk][~np.isnan(concat_labels[kk])], return_counts=True))

sub
0
(array([1]), array([2304]))
sess
0
(array([1, 2, 3]), array([768, 768, 768]))
part
576
(array([1., 2., 3., 4., 5., 6.]), array([288, 288, 288, 288, 288, 288]))
run_in_part
576
(array([1., 2.]), array([864, 864]))
run_overall
0
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36]), array([96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48]))
task
0
(array([1, 2, 3, 4]), array([576, 576, 576, 576]))
map
0
(array([1, 2]), array([1152, 1152]))
run_difficulty
0
(array([ 3,  4,  5,  9, 10, 11, 12, 13]), array([144, 384,  48, 576, 192, 288, 288, 384]))
trial_in_run
0
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47